# Site settings
title: Evan Chime
description: Our personal portfolio site
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evanchime.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Evan Chime
user_description: Software Engineer with 4 years experience focused on supporting large-scale software systems. Excellent experience in analysis, design, development, testing, and implementation of various internet-based applications. Expert in a variety of platforms, languages, and embedded systems. Adept at going beyond that of an engineer to that of a user advocate, designer, developer, and tester. Supportive and enthusiastic team player dedicated to streamlining processes and efficiently resolving project issues.
user_title: Software Engineer
email: evan@softgorithm.com
github_username:  evanchime
linkedin_username: evanchime

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
