# Site settings
title: Evan Chime
description: Our personal portfolio site
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evanchime.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Evan Chime
user_description: Willing to learn. Unassuming. Attentive-to-detail. Problem-solver. Positive attitude. Excellent communication and organizational skills. Seeking a software engineering
  position that builds tools and services that make a positive impact in the daily environment.
 
user_title: Software Engineer
email: evanchime@gmail.com
github_username:  evanchime
#linkedin_username: evanchime

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
