# Site settings
title: Evan Chime
description: Our personal portfolio site
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evanchime.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Evan Chime
user_description: Willing to learn. Innovative software engineer with 5+ years experience. I am a patient thorough person with high attention to detail. Have excellent testing/debugging skills – able to analyse code and engineer well-researched, cost-effective and responsive solutions. 
user_title: Software Engineer
email: evan@softgorithm.com
github_username:  evanchime
linkedin_username: evanchime

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
